/mob/living/carbon/human/attack_hand(mob/user)
	if(user)
		if(user.a_intent != INTENT_HELP)
			for(var/mob/living/simple_animal/hostile/beastmaster/B in beastmaster)
				B.add_beastmaster_enemies(user)
	..()

/mob/living/carbon/human/attack_animal(mob/user)
	if(user)
		for(var/mob/living/simple_animal/hostile/beastmaster/B in beastmaster)
			B.add_beastmaster_enemies(user)
	..()

/mob/living/carbon/human/on_hit(obj/projectile/P)
	. = ..()
	if(P)
		if(P.firer)
			for(var/mob/living/simple_animal/hostile/beastmaster/B in beastmaster)
				B.add_beastmaster_enemies(P.firer)

/mob/living/carbon/human/hitby(atom/movable/AM, skipcatch, hitpush = TRUE, blocked = FALSE, datum/thrownthing/throwingdatum)
	. = ..()
	if(throwingdatum)
		if(throwingdatum.thrower)
			for(var/mob/living/simple_animal/hostile/beastmaster/B in beastmaster)
				B.add_beastmaster_enemies(throwingdatum.thrower)

/mob/living/carbon/human/attackby(obj/item/W, mob/living/user, params)
	. = ..()
	if(user)
		if(W.force)
			for(var/mob/living/simple_animal/hostile/beastmaster/B in beastmaster)
				B.add_beastmaster_enemies(user)

/mob/living/carbon/human/grabbedby(mob/living/carbon/user, supress_message = FALSE)
	. = ..()
	for(var/mob/living/simple_animal/hostile/beastmaster/B in beastmaster)
		B.add_beastmaster_enemies(user)

/mob/living/carbon/human/pointed(atom/A as mob|obj|turf in view(client.view, src))
	if(..())
		if(isliving(A))
			for(var/mob/living/simple_animal/hostile/beastmaster/B in beastmaster)
				B.add_beastmaster_enemies(A)
//				B.GiveTarget(A)
